// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0-devel
// 	protoc        v3.11.4
// source: tensorflow/core/debug/debugger_event_metadata.proto

package debug

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Encapsulates per-event data related to debugging.
type DebuggerEventMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Device     string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	OutputSlot int32  `protobuf:"varint,2,opt,name=output_slot,json=outputSlot,proto3" json:"output_slot,omitempty"`
	NumChunks  int32  `protobuf:"varint,3,opt,name=num_chunks,json=numChunks,proto3" json:"num_chunks,omitempty"`
	ChunkIndex int32  `protobuf:"varint,4,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
}

func (x *DebuggerEventMetadata) Reset() {
	*x = DebuggerEventMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_core_debug_debugger_event_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DebuggerEventMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebuggerEventMetadata) ProtoMessage() {}

func (x *DebuggerEventMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_core_debug_debugger_event_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebuggerEventMetadata.ProtoReflect.Descriptor instead.
func (*DebuggerEventMetadata) Descriptor() ([]byte, []int) {
	return file_tensorflow_core_debug_debugger_event_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *DebuggerEventMetadata) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DebuggerEventMetadata) GetOutputSlot() int32 {
	if x != nil {
		return x.OutputSlot
	}
	return 0
}

func (x *DebuggerEventMetadata) GetNumChunks() int32 {
	if x != nil {
		return x.NumChunks
	}
	return 0
}

func (x *DebuggerEventMetadata) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

var File_tensorflow_core_debug_debugger_event_metadata_proto protoreflect.FileDescriptor

var file_tensorflow_core_debug_debugger_event_metadata_proto_rawDesc = []byte{
	0x0a, 0x33, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x2f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x67, 0x65, 0x72,
	0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x21, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x72,
	0x74, 0x79, 0x2e, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x64, 0x65, 0x62, 0x75, 0x67, 0x22, 0x90, 0x01, 0x0a, 0x15, 0x44, 0x65, 0x62,
	0x75, 0x67, 0x67, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6e,
	0x75, 0x6d, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x6e, 0x75, 0x6d, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x22, 0x5a, 0x20, 0x74,
	0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tensorflow_core_debug_debugger_event_metadata_proto_rawDescOnce sync.Once
	file_tensorflow_core_debug_debugger_event_metadata_proto_rawDescData = file_tensorflow_core_debug_debugger_event_metadata_proto_rawDesc
)

func file_tensorflow_core_debug_debugger_event_metadata_proto_rawDescGZIP() []byte {
	file_tensorflow_core_debug_debugger_event_metadata_proto_rawDescOnce.Do(func() {
		file_tensorflow_core_debug_debugger_event_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_tensorflow_core_debug_debugger_event_metadata_proto_rawDescData)
	})
	return file_tensorflow_core_debug_debugger_event_metadata_proto_rawDescData
}

var file_tensorflow_core_debug_debugger_event_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tensorflow_core_debug_debugger_event_metadata_proto_goTypes = []interface{}{
	(*DebuggerEventMetadata)(nil), // 0: third_party.tensorflow.core.debug.DebuggerEventMetadata
}
var file_tensorflow_core_debug_debugger_event_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tensorflow_core_debug_debugger_event_metadata_proto_init() }
func file_tensorflow_core_debug_debugger_event_metadata_proto_init() {
	if File_tensorflow_core_debug_debugger_event_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tensorflow_core_debug_debugger_event_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DebuggerEventMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tensorflow_core_debug_debugger_event_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tensorflow_core_debug_debugger_event_metadata_proto_goTypes,
		DependencyIndexes: file_tensorflow_core_debug_debugger_event_metadata_proto_depIdxs,
		MessageInfos:      file_tensorflow_core_debug_debugger_event_metadata_proto_msgTypes,
	}.Build()
	File_tensorflow_core_debug_debugger_event_metadata_proto = out.File
	file_tensorflow_core_debug_debugger_event_metadata_proto_rawDesc = nil
	file_tensorflow_core_debug_debugger_event_metadata_proto_goTypes = nil
	file_tensorflow_core_debug_debugger_event_metadata_proto_depIdxs = nil
}
