// Protocol message for the fast Example parse unit test.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0-devel
// 	protoc        v3.11.4
// source: tensorflow/core/util/example_proto_fast_parsing_test.proto

package util

import (
	example "github.com/Golang-Tools/tensorflow_service_apis/tensorflow/tensorflow/core/example"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// This message is parallel to Example, but with additional fields to test
// unknown fields handling in example_proto_fast_parsing_test.cc.
type ExampleWithExtras struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Features *example.Features `protobuf:"bytes,1,opt,name=features,proto3" json:"features,omitempty"`
	Extra1   string            `protobuf:"bytes,1337,opt,name=extra1,proto3" json:"extra1,omitempty"`
	Extra2   int64             `protobuf:"varint,1338,opt,name=extra2,proto3" json:"extra2,omitempty"`
	Extra3   uint32            `protobuf:"fixed32,1339,opt,name=extra3,proto3" json:"extra3,omitempty"`
	Extra4   uint64            `protobuf:"fixed64,1340,opt,name=extra4,proto3" json:"extra4,omitempty"`
	Extra5   float64           `protobuf:"fixed64,1341,opt,name=extra5,proto3" json:"extra5,omitempty"`
	Extra6   []float32         `protobuf:"fixed32,1342,rep,packed,name=extra6,proto3" json:"extra6,omitempty"`
	Extra7   *example.Features `protobuf:"bytes,1343,opt,name=extra7,proto3" json:"extra7,omitempty"`
}

func (x *ExampleWithExtras) Reset() {
	*x = ExampleWithExtras{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_core_util_example_proto_fast_parsing_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExampleWithExtras) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleWithExtras) ProtoMessage() {}

func (x *ExampleWithExtras) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_core_util_example_proto_fast_parsing_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleWithExtras.ProtoReflect.Descriptor instead.
func (*ExampleWithExtras) Descriptor() ([]byte, []int) {
	return file_tensorflow_core_util_example_proto_fast_parsing_test_proto_rawDescGZIP(), []int{0}
}

func (x *ExampleWithExtras) GetFeatures() *example.Features {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *ExampleWithExtras) GetExtra1() string {
	if x != nil {
		return x.Extra1
	}
	return ""
}

func (x *ExampleWithExtras) GetExtra2() int64 {
	if x != nil {
		return x.Extra2
	}
	return 0
}

func (x *ExampleWithExtras) GetExtra3() uint32 {
	if x != nil {
		return x.Extra3
	}
	return 0
}

func (x *ExampleWithExtras) GetExtra4() uint64 {
	if x != nil {
		return x.Extra4
	}
	return 0
}

func (x *ExampleWithExtras) GetExtra5() float64 {
	if x != nil {
		return x.Extra5
	}
	return 0
}

func (x *ExampleWithExtras) GetExtra6() []float32 {
	if x != nil {
		return x.Extra6
	}
	return nil
}

func (x *ExampleWithExtras) GetExtra7() *example.Features {
	if x != nil {
		return x.Extra7
	}
	return nil
}

var File_tensorflow_core_util_example_proto_fast_parsing_test_proto protoreflect.FileDescriptor

var file_tensorflow_core_util_example_proto_fast_parsing_test_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x61, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x72, 0x73, 0x69, 0x6e,
	0x67, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x1a, 0x25, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x2f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x8a, 0x02, 0x0a, 0x11, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x57, 0x69, 0x74, 0x68, 0x45,
	0x78, 0x74, 0x72, 0x61, 0x73, 0x12, 0x30, 0x0a, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x08, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x06, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x31, 0x18, 0xb9, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x78, 0x74, 0x72, 0x61, 0x31,
	0x12, 0x17, 0x0a, 0x06, 0x65, 0x78, 0x74, 0x72, 0x61, 0x32, 0x18, 0xba, 0x0a, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x65, 0x78, 0x74, 0x72, 0x61, 0x32, 0x12, 0x17, 0x0a, 0x06, 0x65, 0x78, 0x74,
	0x72, 0x61, 0x33, 0x18, 0xbb, 0x0a, 0x20, 0x01, 0x28, 0x07, 0x52, 0x06, 0x65, 0x78, 0x74, 0x72,
	0x61, 0x33, 0x12, 0x17, 0x0a, 0x06, 0x65, 0x78, 0x74, 0x72, 0x61, 0x34, 0x18, 0xbc, 0x0a, 0x20,
	0x01, 0x28, 0x06, 0x52, 0x06, 0x65, 0x78, 0x74, 0x72, 0x61, 0x34, 0x12, 0x17, 0x0a, 0x06, 0x65,
	0x78, 0x74, 0x72, 0x61, 0x35, 0x18, 0xbd, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x65, 0x78,
	0x74, 0x72, 0x61, 0x35, 0x12, 0x17, 0x0a, 0x06, 0x65, 0x78, 0x74, 0x72, 0x61, 0x36, 0x18, 0xbe,
	0x0a, 0x20, 0x03, 0x28, 0x02, 0x52, 0x06, 0x65, 0x78, 0x74, 0x72, 0x61, 0x36, 0x12, 0x2d, 0x0a,
	0x06, 0x65, 0x78, 0x74, 0x72, 0x61, 0x37, 0x18, 0xbf, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x46, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x52, 0x06, 0x65, 0x78, 0x74, 0x72, 0x61, 0x37, 0x42, 0x24, 0x5a, 0x1f,
	0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x74, 0x65, 0x6e, 0x73, 0x6f,
	0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0xf8,
	0x01, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tensorflow_core_util_example_proto_fast_parsing_test_proto_rawDescOnce sync.Once
	file_tensorflow_core_util_example_proto_fast_parsing_test_proto_rawDescData = file_tensorflow_core_util_example_proto_fast_parsing_test_proto_rawDesc
)

func file_tensorflow_core_util_example_proto_fast_parsing_test_proto_rawDescGZIP() []byte {
	file_tensorflow_core_util_example_proto_fast_parsing_test_proto_rawDescOnce.Do(func() {
		file_tensorflow_core_util_example_proto_fast_parsing_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_tensorflow_core_util_example_proto_fast_parsing_test_proto_rawDescData)
	})
	return file_tensorflow_core_util_example_proto_fast_parsing_test_proto_rawDescData
}

var file_tensorflow_core_util_example_proto_fast_parsing_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tensorflow_core_util_example_proto_fast_parsing_test_proto_goTypes = []interface{}{
	(*ExampleWithExtras)(nil), // 0: tensorflow.ExampleWithExtras
	(*example.Features)(nil),  // 1: tensorflow.Features
}
var file_tensorflow_core_util_example_proto_fast_parsing_test_proto_depIdxs = []int32{
	1, // 0: tensorflow.ExampleWithExtras.features:type_name -> tensorflow.Features
	1, // 1: tensorflow.ExampleWithExtras.extra7:type_name -> tensorflow.Features
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tensorflow_core_util_example_proto_fast_parsing_test_proto_init() }
func file_tensorflow_core_util_example_proto_fast_parsing_test_proto_init() {
	if File_tensorflow_core_util_example_proto_fast_parsing_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tensorflow_core_util_example_proto_fast_parsing_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExampleWithExtras); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tensorflow_core_util_example_proto_fast_parsing_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tensorflow_core_util_example_proto_fast_parsing_test_proto_goTypes,
		DependencyIndexes: file_tensorflow_core_util_example_proto_fast_parsing_test_proto_depIdxs,
		MessageInfos:      file_tensorflow_core_util_example_proto_fast_parsing_test_proto_msgTypes,
	}.Build()
	File_tensorflow_core_util_example_proto_fast_parsing_test_proto = out.File
	file_tensorflow_core_util_example_proto_fast_parsing_test_proto_rawDesc = nil
	file_tensorflow_core_util_example_proto_fast_parsing_test_proto_goTypes = nil
	file_tensorflow_core_util_example_proto_fast_parsing_test_proto_depIdxs = nil
}
